// Generated by https://quicktype.io

export interface ProductDto {
  id:          number;
  title:       string;
  price:       number;
  description: string;
  category:    string;
  image:       string;
  rating:      Rating;
}

export interface ProductData extends ProductDto {

}

export interface Rating {
  rate:  number;
  count: number;
}
